import '@servicenow/sdk/global'
import { RestApi } from '@servicenow/sdk/core'
import {
    listPortfolios,
    createPortfolio,
    updatePortfolio,
    getPortfolio,
    getPortfolioViews,
    getPortfolioViewData,
    getPortfolioTimeline,
    getPortfolioDashboard,
    getPortfolioProgress,
    getPortfolioWorkload,
    linkPortfolioProject,
    unlinkPortfolioProject,
    getProjectPortfolios,
} from '../../server/rest/portfolio-routes'
import {
    listProjects,
    createProject,
    updateProject,
    createProjectTask,
    getProject,
    getProjectSections,
    createProjectSection,
    updateProjectSection,
    deleteProjectSection,
    reorderProjectSections,
    reorderTaskList,
    getProjectBoard,
    getProjectTasks,
    getTask,
    getTaskProjects,
    updateTask,
    reorderBoard,
} from '../../server/rest/project-routes'
import {
    getView,
    updateView,
    listCustomFields,
    listCustomFieldValues,
    upsertCustomFieldValues,
} from '../../server/rest/view-routes'
import {
    listCapacityPlans,
    getCapacityPlan,
    getCapacityPlanGrid,
    getCapacityPlanAllocations,
    updateCapacityPlanAllocation,
    searchUsers,
    searchGroups,
    getTeamMembers,
} from '../../server/rest/capacity-routes'
import { listAutomations, listIntakeForms } from '../../server/rest/config-routes'
import {
    listProjectMembers,
    addProjectMember,
    updateProjectMember,
    removeProjectMember,
    listPortfolioMembers,
    addPortfolioMember,
    updatePortfolioMember,
    removePortfolioMember,
} from '../../server/rest/member-routes'

RestApi({
    $id: Now.ID['z-inflow-rest-api'],
    name: 'Z-Inflow REST API',
    serviceId: 'v1',
    namespace: 'x_gzi_zscaler_ppm',
    consumes: 'application/json',
    produces: 'application/json',
    shortDescription: 'Scoped REST API for Z-Inflow portfolio, project, capacity, and identity operations',
    routes: [
        { $id: Now.ID['route-portfolios-get'], name: 'List Portfolios', method: 'GET', path: '/portfolios', script: listPortfolios },
        { $id: Now.ID['route-portfolios-post'], name: 'Create Portfolio', method: 'POST', path: '/portfolios', script: createPortfolio },
        { $id: Now.ID['route-portfolio-get'], name: 'Get Portfolio', method: 'GET', path: '/portfolios/{id}', script: getPortfolio },
        { $id: Now.ID['route-portfolio-patch'], name: 'Update Portfolio', method: 'PATCH', path: '/portfolios/{id}', script: updatePortfolio },
        { $id: Now.ID['route-portfolio-views-get'], name: 'Portfolio Views', method: 'GET', path: '/portfolios/{id}/views', script: getPortfolioViews },
        { $id: Now.ID['route-portfolio-view-data-get'], name: 'Portfolio View Data', method: 'GET', path: '/portfolios/{id}/views/{viewId}/data', script: getPortfolioViewData },
        { $id: Now.ID['route-portfolio-timeline-get'], name: 'Portfolio Timeline', method: 'GET', path: '/portfolios/{id}/timeline', script: getPortfolioTimeline },
        { $id: Now.ID['route-portfolio-dashboard-get'], name: 'Portfolio Dashboard', method: 'GET', path: '/portfolios/{id}/dashboard', script: getPortfolioDashboard },
        { $id: Now.ID['route-portfolio-progress-get'], name: 'Portfolio Progress', method: 'GET', path: '/portfolios/{id}/progress', script: getPortfolioProgress },
        { $id: Now.ID['route-portfolio-workload-get'], name: 'Portfolio Workload', method: 'GET', path: '/portfolios/{id}/workload', script: getPortfolioWorkload },
        { $id: Now.ID['route-portfolio-projects-post'], name: 'Link Portfolio Project', method: 'POST', path: '/portfolios/{id}/projects', script: linkPortfolioProject },
        { $id: Now.ID['route-portfolio-projects-delete'], name: 'Unlink Portfolio Project', method: 'DELETE', path: '/portfolios/{id}/projects/{projectId}', script: unlinkPortfolioProject },
        { $id: Now.ID['route-project-portfolios-get'], name: 'Project Portfolios', method: 'GET', path: '/projects/{id}/portfolios', script: getProjectPortfolios },
        { $id: Now.ID['route-projects-get'], name: 'List Projects', method: 'GET', path: '/projects', script: listProjects },
        { $id: Now.ID['route-projects-post'], name: 'Create Project', method: 'POST', path: '/projects', script: createProject },
        { $id: Now.ID['route-project-get'], name: 'Get Project', method: 'GET', path: '/projects/{id}', script: getProject },
        { $id: Now.ID['route-project-patch'], name: 'Update Project', method: 'PATCH', path: '/projects/{id}', script: updateProject },
        { $id: Now.ID['route-project-members-get'], name: 'List Project Members', method: 'GET', path: '/projects/{id}/members', script: listProjectMembers },
        { $id: Now.ID['route-project-members-post'], name: 'Add Project Member', method: 'POST', path: '/projects/{id}/members', script: addProjectMember },
        { $id: Now.ID['route-project-member-patch'], name: 'Update Project Member', method: 'PATCH', path: '/projects/{id}/members/{memberId}', script: updateProjectMember },
        { $id: Now.ID['route-project-member-delete'], name: 'Remove Project Member', method: 'DELETE', path: '/projects/{id}/members/{memberId}', script: removeProjectMember },
        { $id: Now.ID['route-portfolio-members-get'], name: 'List Portfolio Members', method: 'GET', path: '/portfolios/{id}/members', script: listPortfolioMembers },
        { $id: Now.ID['route-portfolio-members-post'], name: 'Add Portfolio Member', method: 'POST', path: '/portfolios/{id}/members', script: addPortfolioMember },
        { $id: Now.ID['route-portfolio-member-patch'], name: 'Update Portfolio Member', method: 'PATCH', path: '/portfolios/{id}/members/{memberId}', script: updatePortfolioMember },
        { $id: Now.ID['route-portfolio-member-delete'], name: 'Remove Portfolio Member', method: 'DELETE', path: '/portfolios/{id}/members/{memberId}', script: removePortfolioMember },
        { $id: Now.ID['route-project-sections-get'], name: 'Project Sections', method: 'GET', path: '/projects/{id}/sections', script: getProjectSections },
        { $id: Now.ID['route-project-sections-post'], name: 'Create Project Section', method: 'POST', path: '/projects/{id}/section', script: createProjectSection },
        { $id: Now.ID['route-project-section-post'], name: 'Create Project Section (alias)', method: 'POST', path: '/projects/{id}/section', script: createProjectSection },
        { $id: Now.ID['route-project-sections-reorder-patch'], name: 'Reorder Project Sections', method: 'PATCH', path: '/projects/{id}/sections/reorder', script: reorderProjectSections },
        { $id: Now.ID['route-project-section-patch'], name: 'Update Project Section', method: 'PATCH', path: '/projects/{id}/sections/{sectionId}', script: updateProjectSection },
        { $id: Now.ID['route-project-section-delete'], name: 'Delete Project Section', method: 'DELETE', path: '/projects/{id}/sections/{sectionId}', script: deleteProjectSection },
        { $id: Now.ID['route-project-task-list-patch'], name: 'Reorder Task List', method: 'PATCH', path: '/projects/{id}/task-list', script: reorderTaskList },
        { $id: Now.ID['route-project-board-get'], name: 'Project Board', method: 'GET', path: '/projects/{id}/board', script: getProjectBoard },
        { $id: Now.ID['route-project-board-patch'], name: 'Reorder Board', method: 'PATCH', path: '/projects/{id}/board', script: reorderBoard },
        { $id: Now.ID['route-project-tasks-get'], name: 'Project Tasks', method: 'GET', path: '/projects/{id}/tasks', script: getProjectTasks },
        { $id: Now.ID['route-project-tasks-post'], name: 'Create Project Task', method: 'POST', path: '/projects/{id}/tasks', script: createProjectTask },
        { $id: Now.ID['route-task-get'], name: 'Get Task', method: 'GET', path: '/tasks/{id}', script: getTask },
        { $id: Now.ID['route-task-patch'], name: 'Update Task', method: 'PATCH', path: '/tasks/{id}', script: updateTask },
        { $id: Now.ID['route-task-projects-get'], name: 'Task Projects', method: 'GET', path: '/tasks/{id}/projects', script: getTaskProjects },
        { $id: Now.ID['route-view-get'], name: 'Get View', method: 'GET', path: '/views/{id}', script: getView },
        { $id: Now.ID['route-view-patch'], name: 'Update View', method: 'PATCH', path: '/views/{id}', script: updateView },
        { $id: Now.ID['route-custom-fields-get'], name: 'List Custom Fields', method: 'GET', path: '/custom-fields', script: listCustomFields },
        { $id: Now.ID['route-custom-field-values-get'], name: 'List Custom Field Values', method: 'GET', path: '/custom-fields/values', script: listCustomFieldValues },
        { $id: Now.ID['route-custom-field-values-post'], name: 'Upsert Custom Field Values', method: 'POST', path: '/custom-fields/values', script: upsertCustomFieldValues },
        { $id: Now.ID['route-capacity-plans-get'], name: 'List Capacity Plans', method: 'GET', path: '/capacity/plans', script: listCapacityPlans },
        { $id: Now.ID['route-capacity-plan-get'], name: 'Get Capacity Plan', method: 'GET', path: '/capacity/plans/{id}', script: getCapacityPlan },
        { $id: Now.ID['route-capacity-plan-grid-get'], name: 'Capacity Plan Grid', method: 'GET', path: '/capacity/plans/{id}/grid', script: getCapacityPlanGrid },
        { $id: Now.ID['route-capacity-plan-allocations-get'], name: 'Capacity Plan Allocations', method: 'GET', path: '/capacity/plans/{id}/allocations', script: getCapacityPlanAllocations },
        { $id: Now.ID['route-capacity-plan-allocation-patch'], name: 'Update Capacity Allocation', method: 'PATCH', path: '/capacity/plans/{id}/allocations/{allocationId}', script: updateCapacityPlanAllocation },
        { $id: Now.ID['route-users-search-get'], name: 'Search Users', method: 'GET', path: '/users/search', script: searchUsers },
        { $id: Now.ID['route-groups-search-get'], name: 'Search Groups', method: 'GET', path: '/groups/search', script: searchGroups },
        { $id: Now.ID['route-team-members-get'], name: 'Team Members', method: 'GET', path: '/teams/{id}/members', script: getTeamMembers },
        { $id: Now.ID['route-automations-get'], name: 'List Automations', method: 'GET', path: '/automations', script: listAutomations },
        { $id: Now.ID['route-intake-forms-get'], name: 'List Intake Forms', method: 'GET', path: '/intake-forms', script: listIntakeForms },
    ],
})
